[project]
name = "meticulous-watcher"
version = "0.1.0"
description = "Meticulous Espresso Machine Watcher"
requires-python = ">=3.11"
dependencies = [
    "tornado",
    "python-engineio==4.6.1",
    "python-socketio==5.8.0",
    "sdnotify==0.3.2",
    "systemd-python",
    "psutil",
]

[tool.black]
# Do not touch the submodule, it has its own formatter
extend-exclude = "/log_redactor/"
